
PROBABILIDAD_ACTITUD_DEFENSIVA = 0.6

ACTITUD_DEFENSIVA = 1
ACTITUD_OFENSIVA = 2

RUTA_ARCHIVOS_TEMPORARIOS = ''

TRANSFORMACION_MAXIMA_EN_ESPECIA = 5
EJERCITOS_POR_ESPECIA = 2
COSECHA_MINIMA_GANADORA = 100
